In [1]:
import numpy as np
print('done')

done


In [2]:
a = np.arange(10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)
# Array a
print(a)

# Array b
print('\n',b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [[10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
np.random.seed(0)
dt = np.random.randint(0, 100, (10,10))
dt

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58, 65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72,  9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0,  0, 36, 53,  5, 38],
       [17, 79,  4, 42, 58, 31,  1, 65, 41, 57],
       [35, 11, 46, 82, 91,  0, 14, 99, 53, 12],
       [42, 84, 75, 68,  6, 68, 47,  3, 76, 52],
       [78, 15, 20, 99, 58, 23, 79, 13, 85, 48]])

In [4]:
vls = np.arange(50, dtype = float).reshape(5,10)
vls

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [5]:
vls[0,4] = np.nan
vls

array([[ 0.,  1.,  2.,  3., nan,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [6]:
vls[3,7] = np.nan
vls

array([[ 0.,  1.,  2.,  3., nan,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., nan, 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])

In [7]:
np.isnan(vls).sum()

2

In [8]:
vls[np.isnan(vls)] = 0
np.median(vls)

23.5

In [9]:
dt

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58, 65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72,  9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88, 49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57, 32, 31, 74, 23, 35],
       [75, 55, 28, 34,  0,  0, 36, 53,  5, 38],
       [17, 79,  4, 42, 58, 31,  1, 65, 41, 57],
       [35, 11, 46, 82, 91,  0, 14, 99, 53, 12],
       [42, 84, 75, 68,  6, 68, 47,  3, 76, 52],
       [78, 15, 20, 99, 58, 23, 79, 13, 85, 48]])

# Normalização min max

In [10]:
x_norm = (dt - dt.min(axis = 0))/(dt.max(axis = 0) - dt.min(axis = 0))
print(x_norm)

[[0.421875   0.46753247 0.71428571 0.64444444 0.73626374 0.13235294
  1.         0.1875     0.3875     0.98684211]
 [0.828125   1.         1.         0.03333333 0.63736264 0.95588235
  0.46341463 0.875      0.5125     1.        ]
 [1.         0.33766234 0.25       0.75555556 0.79120879 0.13235294
  0.23170732 0.80208333 0.8        0.88157895]
 [0.46875    0.68831169 0.92857143 1.         0.96703297 0.72058824
  0.34146341 0.16666667 0.175      0.02631579]
 [0.34375    0.27272727 0.72619048 0.         0.62637363 0.47058824
  0.36585366 0.73958333 0.225      0.30263158]
 [0.90625    0.57142857 0.28571429 0.27777778 0.         0.
  0.42682927 0.52083333 0.         0.34210526]
 [0.         0.88311688 0.         0.36666667 0.63736264 0.45588235
  0.         0.64583333 0.45       0.59210526]
 [0.28125    0.         0.5        0.81111111 1.         0.
  0.15853659 1.         0.6        0.        ]
 [0.390625   0.94805195 0.8452381  0.65555556 0.06593407 1.
  0.56097561 0.         0.8875     0

# Usando o KNN e fazendo normalização dos dados(Standard) Z-score

In [11]:
a = np.array([1.65, 1.85, 1.88])
p = np.array([75,90,80])

# Z-score( Standardnization)
# z = x - ~x/std(x)
tableau = np.vstack((a,p)).T
tableau

# normalizão Padronizada
tableau_normalisé = (tableau - np.mean(tableau, axis = 0))/np.std(tableau, axis = 0)

In [12]:
np.column_stack((a, p))

array([[ 1.65, 75.  ],
       [ 1.85, 90.  ],
       [ 1.88, 80.  ]])

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# Dados
altura = np.array([1.65, 1.85, 1.88]) 
peso = np.array([75, 90, 80])

# Normalização (Z-score)
scaler = StandardScaler()
X = np.column_stack((altura, peso))
X_normalized = scaler.fit_transform(X)

# Definição de labels (0 - Pequena, 1 - Grande)
# Assumindo que as duas primeiras pessoas são consideradas "grandes" e a última "pequena"
y = np.array([1, 1, 0])

# Treinamento do modelo
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_normalized, y)

# Previsão para novos dados
# Por exemplo, altura = 1.75m e peso = 85kg
new_data = np.array([[1.85, 80]])
new_data_normalized = scaler.transform(new_data)
prediction = knn.predict(new_data_normalized)

Alt = ['Pequeno', 'Grande']
prediction
print(Alt[prediction[0]])
print(prediction)


In [14]:
X_normalized

array([[-1.40399977, -1.06904497],
       [ 0.55506968,  1.33630621],
       [ 0.84893009, -0.26726124]])

In [15]:
tableau_normalisé

array([[-1.40399977, -1.06904497],
       [ 0.55506968,  1.33630621],
       [ 0.84893009, -0.26726124]])

In [1]:
import flet as ft

def main(page: ft.Page):
    # Adiciona um texto com "Hello, World!" à página
    hello_text = ft.Text(value="Hello, World!", size=30)
    page.add(hello_text)

# Executa a aplicação
ft.app(target=main)


Exception in thread Thread-5:
Traceback (most recent call last):
  File "c:\Users\jeova\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\Users\jeova\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\jeova\AppData\Local\Programs\Python\Python37\lib\site-packages\flet_runtime\sync_local_socket_connection.py", line 150, in __connection_loop
    self.__connection, client_address = self.__sock.accept()
  File "c:\Users\jeova\AppData\Local\Programs\Python\Python37\lib\socket.py", line 212, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] Une opération a été tentée sur autre chose qu’un socket

