# Broadcasting



In [1]:
import numpy as np
print('done')

done


In [3]:
np.random.seed(0)
a = np.random.randint(0,10,(2,5))
print(a)

[[5 0 3 3 7]
 [9 3 5 2 4]]


In [5]:
b = np.ones((2,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Regras

### 1- Tem que ser dimensoes iguais seja na linha como na coluna

In [12]:
# Exemplo:
display(a.shape)
display(b.shape)

# Fazendo a soma
print(f"resultado: \n{a * b}")

(2, 5)

(2, 5)

resultado: 
[[5. 0. 3. 3. 7.]
 [9. 3. 5. 2. 4.]]


### 2 - As linhas podem ser diferententes ou iguais e a coluna = 1 para poder fazer operações com um outro tipo de matriz


In [24]:
# Exemplo
display(a.shape)
c = np.array([[3], [1]])
display(c.shape)

# Fazendo a operação
print('Resutado: \n', a + c)

(2, 5)

(2, 1)

Resutado: 
 [[ 8  3  6  6 10]
 [10  4  6  3  5]]


In [53]:
# Exemplos2 
d = np.array([[1], [2], [3], [4]])
e = np.ones((1,3))
display(d)
display(e)

# fazendo a operação
display(d+e)

array([[1],
       [2],
       [3],
       [4]])

array([[1., 1., 1.]])

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])