# Numpy

In [2]:
import numpy as np
print('done')

done


In [3]:
array = [12, 3, 4, 11, 34,11]
a = np.array(array)
a

array([12,  3,  4, 11, 34, 11])

## Atributos
      ndim: ver a quantidade de dimensões que a lista
      shape: retorna uma tupla do array que representa cada dimensão (L, C)
      size: retorna quantidade de elementos que ha na lista

In [4]:
print(f'Essa lista so tem {a.ndim} dimensão')

Essa lista so tem 1 dimensão


In [5]:
print(f'Shape{a.shape}') # isso indeca que so tem 5 linhas

Shape(6,)


In [6]:
print(f'Essa lista tem {a.size} elementos')

Essa lista tem 6 elementos


### Travailler avec la variable array2

In [7]:
qnt = 0
for res in a:
    qnt +=1
print(f'Essa lista tem {qnt} elementos')

Essa lista tem 6 elementos


In [8]:
array2 = [[34,11, 45], [3,4,55]] 
a2 = np.array(array2)
a2

array([[34, 11, 45],
       [ 3,  4, 55]])

In [9]:
d = a2.ndim
print(f'Essa lista tem {d} dimensões')

Essa lista tem 2 dimensões


In [10]:
# vendo o shape ou forma
frm = a2.shape
print(frm)

(2, 3)


In [11]:
# vendo quantos elementos essa lista tem
q_element = a2.size
print(f'Essa lista tem {q_element} elementos')

Essa lista tem 6 elementos


# Criação de arrays...
**np.arange()**: cria um array definindo o inicio ate ao fim


In [12]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


**np.array()**: cria um array a partir de um objecto ou interavel 

In [13]:
lista = [3, 11, 4]
nouvau_array = np.array(lista)
print(nouvau_array)

[ 3 11  4]


**np.identity**: Cria uma matriz identidade. onde recebe o parametro de quantas linhas deve ter

In [14]:
matriz_I = np.identity(3)
print(matriz_I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**np.ones()**: Cria uma matriz de Uns(1). Onde recebe o paramentro de quntas linhas deve ter. sempre sera mxn (linha, coluna)

In [15]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**np.zeros()**: Cria uma matriz de Zeros(0). Onde recebe o paramentro de quntas linhas deve ter. sempre sera mxn (linha, coluna)

In [16]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Oprações  Matematicas com Numpy

In [17]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


## Sum()
**sum()**: função para somar valores numa matriz

In [18]:
soma = np.sum(a)
print(f"A soma da matriz {a} é igual a {soma}")

A soma da matriz [1 2 3 4 5 6 7 8 9] é igual a 45


In [19]:
v = np.array([[
            [23, 2], [23, 1], [3, 23]
    ]])
print(v)

[[[23  2]
  [23  1]
  [ 3 23]]]


In [20]:
v.shape

(1, 3, 2)

In [21]:
v.shape

(1, 3, 2)

In [22]:
v.size # a soma do shape

6

In [23]:
x = [12, 3, 4, 55]
len(x)
res = np.array(x)
res

array([12,  3,  4, 55])

In [24]:
np.full((3, 4), 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [25]:
np.random.seed(0)
v = np.random.randn(25)
print(v)
print("O maior numero é: ",v.max())
print("O menor numero é: ",v.min())

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985   0.14404357  1.45427351
  0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826
  0.3130677  -0.85409574 -2.55298982  0.6536186   0.8644362  -0.74216502
  2.26975462]
O maior numero é:  2.2697546239876076
O menor numero é:  -2.5529898158340787


In [26]:
nomes = ["Jeovani", "Carlos", 'Vanda', 'Sandra']
np.random.choice(nomes)

'Jeovani'

In [27]:
lin = np.linspace(0,10,5, dtype= np.float16)
display(lin)

array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float16)

# Manupulation

In [41]:
a_ones = np.ones((3,2))
a_zeros = np.zeros((3,2))

print(f"{a_ones}")
print(f"\n{a_zeros} ")


[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]] 


### Unido dados no sentido horizontal

In [42]:
joining_H = np.hstack((a_ones, a_zeros))

display(joining_H)
print(joining_H.shape)
print("A lista tem",joining_H.size, 'elementos')

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

(3, 4)
A lista tem 12 elementos


### Unido dados no sentido vertical

In [45]:
joining_V = np.vstack((a_zeros,a_ones))
print(joining_V)
print(f"\nTamanho = {joining_V.shape}")
print(f"A lista tem {joining_V.size} elementos")

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Tamanho = (6, 2)
A lista tem 12 elementos


# np.concatenate()

In [60]:
jvc = np.concatenate((a_ones, a_zeros), axis = 0) # vertical
jhc = np.concatenate((a_ones, a_zeros), axis = 1) # horizontal

print("Vertical:\n\n",jvc) # printar a lista em vertical
print("\n horizontal: \n\n", jhc) # printar a lista em horizontal

Vertical:

 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

 horizontal: 

 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


# np.reshape((l,c))

In [74]:
list = np.arange(10)
print(list)
print('\n Tamanho da lista:',list.size)
print(list.reshape((2,5)))


[0 1 2 3 4 5 6 7 8 9]

 Tamanho da lista: 10
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [76]:
# Obs: Tentar fazer a mesma coisa, só que com dicionarios. 
list = list.ravel() # serve para por uma lista/ em uma unica dimenssão ou em uma unica linha
print(list) 
"""
Esse metodo sera util quando trabalharmos com sklearn e numpy para criamos algorimos de ML
"""

[0 1 2 3 4 5 6 7 8 9]
