# Exercice
Standardisez la matrice A sur chaque colonne.
A - ~A/std(A)

Resultat: chaque colonne doit avoir moyenne = 0 et écart type = 1 Praticamente pediram para fazer normalização

Z= X−μ/ σ

 
Onde:


X é o valor original,

μ é a média da matriz,

σ é o desvio padrão da matriz.

In [1]:
import numpy as np
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [5]:
media = np.median(A, axis=0)
display(media)

std = np.std(A, axis = 0)
display(std)



array([45.5, 38. , 69.5, 41. , 69.5])

array([22.66384786, 22.28003591, 26.5678377 , 29.36341261, 23.2432786 ])

In [6]:
res =  ((A - media)/std)
res

array([[-0.0661847 ,  0.40394908, -0.20701722,  0.88545566, -0.10755798],
       [-1.6104944 ,  2.0197454 , -1.82551552, -0.17027994,  0.75290583],
       [ 1.08101679,  2.24416155,  0.69633066, -0.98762362, -0.49476669],
       [ 0.86040112,  0.04488323,  0.65869117,  0.17027994,  0.79592902],
       [ 1.56637126, -0.04488323, -1.67495754,  1.22601553,  0.10755798],
       [-1.6104944 , -0.80789816,  0.3952147 ,  0.95356764,  0.40872031],
       [ 0.0661847 ,  1.16696401,  0.47049369,  1.97524725,  0.79592902],
       [ 0.15443097, -0.40394908, -1.90079451, -0.74923172, -2.38778707],
       [-0.28680037, -0.26929939, -0.16937773, -1.08979159, -0.53778988],
       [-0.59566231, -0.31418262,  0.16937773, -0.61300777, -1.48430007]])

In [7]:
res.mean(axis = 0)

array([-0.04412313,  0.40394908, -0.33875546,  0.16006314, -0.21511595])