# Matematiques ete Statistiques

### Opeações matematicas com numpy
*   numpy.sum()
*   numpy.prod()
*   numpy.cusmum()
*   numpy.cumprod()


In [1]:
import numpy as np
print("Done.")

Done.


### **numpy.sum()**

In [2]:
a = np.arange(4)
print("array: ",a)
print(a.sum())

array:  [0 1 2 3]
6


In [3]:
# Ex2: 
b = np.arange(25)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
# Como ela funciona.
x = 0
for vls in b:
    x+=vls
print(x)

300


## **numpy.prod()**

In [5]:
k = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(k)

16

In [6]:
k2 = np.arange(1,9)
display(k2)
k2.prod()

array([1, 2, 3, 4, 5, 6, 7, 8])

40320

In [7]:
# como é que ela funciona...
x = 1
for vls in k2:
    x*=vls
print(x)

40320


## **numpy.cusmum()**

In [8]:
a = np.arange(1, 6)
resutlado = a.cumsum()
print(f"Array original: {a}")
print(f"Array aplicando o cumsum: {resutlado}")

Array original: [1 2 3 4 5]
Array aplicando o cumsum: [ 1  3  6 10 15]


## **numpy.cumprod()**

In [9]:
b = np.arange(1, 4)
resutlado_2 = np.cumprod(b)
print(f"Array original: {b}")
print(f"Array aplicando o cumprod: {resutlado_2}")

Array original: [1 2 3]
Array aplicando o cumprod: [1 2 6]


In [10]:
# Exemplo 2
c = np.arange(1,6)
resutlado_3 = np.cumprod(c)
print(f"Array original: {c}")
print(f"Array aplicado o cumprod: {resutlado_3}")

Array original: [1 2 3 4 5]
Array aplicado o cumprod: [  1   2   6  24 120]


In [11]:
arr = [1, 3, 2, 4 ,11]
a = np.array(arr)
print(a)

print(np.sort(a))

[ 1  3  2  4 11]
[ 1  2  3  4 11]
