# Statistiques et Mathématiques

In [2]:
import numpy as np
print('Done.')

Done.


In [66]:
np.random.seed(0)
A = np.random.randint(0,10, (2,3))
A

array([[5, 0, 3],
       [3, 7, 9]])

# Soma()

In [68]:
soma = A.sum()
display("Array:", A)
print(soma)

'Array:'

array([[5, 0, 3],
       [3, 7, 9]])

27


#### com axis = 0 vs axis = 1

In [67]:
A.sum(axis=0) # soma linha por linha

array([ 8,  7, 12])

In [69]:
A.sum(axis= 1)

array([ 8, 19])

## a.cumsum() - Soma comulativa

In [70]:
A.cumsum(axis=0)

array([[ 5,  0,  3],
       [ 8,  7, 12]], dtype=int32)

## a.prod()

In [71]:
A.prod()

0

In [72]:
A.prod(axis = 0)

array([15,  0, 27])

# np.min()

In [73]:
A.min(axis = 1)

array([0, 3])

In [74]:
A.min(axis = 0)

array([3, 0, 3])

In [75]:
A.argmin(axis = 0)

array([1, 0, 0], dtype=int64)

In [76]:
A.argmin(axis = 1)

array([1, 0], dtype=int64)

## np.mean()

In [77]:
media = np.sum(A)/A.size
media

4.5

In [78]:
np.var(A)

8.583333333333334

In [16]:
a = np.array([1,3,4,6])
print(a)
print(f"media é {a.mean()}")

[1 3 4 6]
media é 3.5


In [17]:
dv_p = np.std(a,ddof=1) # ddof = 1 para calcular o desvio padrão amostral.
print(dv_p)

2.0816659994661326


In [18]:
if dv_p < 2:
    print('baixo')
else: print('alto')

alto


In [19]:
np.mean(a)

3.5

In [20]:
mediana = (np.sum(a) - 1)/a.size
mediana

3.25

# Usando o argmin() e argmax()

In [21]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [22]:
print(f'Valor maximo: {a.max()}')
print(f'Valor minimo: {a.min()}')
print(f'A lista tem {a.size} elementos')
print(f'')

Valor maximo: 9
Valor minimo: 1
A lista tem 9 elementos



## Achando(localizando) o indice do valor min()

In [23]:
print(f'O valor {a.min()} esta no indice {a.argmin()}')

O valor 1 esta no indice 0


## Achando(localizando) o indice do valor max()

In [24]:
print(f'O valor {a.max()} esta no indice {a.argmax()}')

O valor 9 esta no indice 8


# np.transpose() - Transposta

In [25]:
array = np.arange(1, 21).reshape(4,5)
display(array)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
T = array.transpose()
print(T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [27]:
print(T.shape)

(5, 4)


# np.dot() - Mutiplicação de valores e de arrays

In [28]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
b = np.arange(11, 21).reshape(5,2)
b

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [30]:
a = np.array(a)
b = np.array(b)
display(a)
display(b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [31]:
np.dot(a,b)

array([[170, 180],
       [545, 580]])

In [32]:
A = np.array([[1, 4], [0, 1]])
B = np.array([[0, 1], [2, 2]])
np.dot(A,B)

array([[8, 9],
       [2, 2]])

# Exercícios

### 1. Crie um array com 10 elementos usando a função arange;

In [33]:
a = np.arange(10)
print(a)
print(f"Esse aray tem {a.ndim} dimensões")

[0 1 2 3 4 5 6 7 8 9]
Esse aray tem 1 dimensões


### 2. Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape;

In [34]:
a_2D = a.reshape(2,5)
print("Resultado:\n",a_2D)
print(f"O array a_2D tem {a_2D.ndim} dimensões")

Resultado:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
O array a_2D tem 2 dimensões


### 3. Crie duas matrizes a partir de dois arrays;

In [35]:
M_A = np.mat(np.array(np.arange(20).reshape(5,4)))
M_B = np.mat(np.array(np.arange(20,40).reshape(4,5)))

print(f"Array M_A: \n {M_A}\n tipo é {type(M_A)}, tem {M_A.ndim} dimensões e tem {M_A.size} elementos")
print(f"Array M_B: \n {M_B}\n tipo é {type(M_B)} e tem {M_B.ndim} dimensões e tem {M_B.size} elementos")



Array M_A: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
 tipo é <class 'numpy.matrix'>, tem 2 dimensões e tem 20 elementos
Array M_B: 
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
 tipo é <class 'numpy.matrix'> e tem 2 dimensões e tem 20 elementos


### 4. Crie duas matrizes e realize a multiplicação das mesmas.


In [36]:
np.dot(M_A, M_B)

matrix([[ 190,  196,  202,  208,  214],
        [ 630,  652,  674,  696,  718],
        [1070, 1108, 1146, 1184, 1222],
        [1510, 1564, 1618, 1672, 1726],
        [1950, 2020, 2090, 2160, 2230]])

In [37]:
np.random.seed(0)
a = np.random.randint(0,10, (2,3))
a

array([[5, 0, 3],
       [3, 7, 9]])

In [38]:
display(a.min(axis=0)) 
display(a.min(axis = 1))

array([3, 0, 3])

array([0, 3])

In [39]:
np.argmin(a, axis = 1)

array([1, 0], dtype=int64)

In [40]:
import pandas as pd
dt = pd.read_csv("pizzas.csv")
dt

,diametro,preco
0,20,50
1,22,55
2,24,60
3,26,65
4,28,70
5,30,75
6,32,80
7,34,85
8,36,90
9,38,95


In [41]:
prix = dt['preco']
prix

0      50
1      55
2      60
3      65
4      70
5      75
6      80
7      85
8      90
9      95
10    100
Name: preco, dtype: int64

In [42]:
np.sum(prix, axis = 0)

825

In [43]:
np.argmin(prix, axis = 0)

0

In [44]:
a.std() # desvio padrao

2.9297326385411577

In [45]:
a.var() # variancia

8.583333333333334

In [46]:
np.corrcoef(a)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [47]:
a2 = np.arange(10).reshape(5,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
b = np.arange(10, 20).reshape(5,2)
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [49]:
x = [1,2,3,4,5]
y = [5,4,3,2,1]
np.corrcoef(x,y)

array([[ 1., -1.],
       [-1.,  1.]])

In [65]:
np.array(dt['preco'])

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100], dtype=int64)

# np.unique() - Para ver o numero de elementos que se repetem

In [89]:
print("Array:\n",A)
print(f"Resultado: {np.unique(A, return_counts=True)}")

Array:
 [[5 0 3]
 [3 7 9]]
Resultado: (array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))


In [103]:
values, counts = np.unique(A, return_counts=True)
display(values)
display(counts)

array([0, 3, 5, 7, 9])

array([1, 2, 1, 1, 1], dtype=int64)

O objectivo desta parte é organizar os dados e ver quais são os numeros que se repetem deste o inicio até ao fim onde o numero que se encotra no fim é o que mais se repte.

In [102]:
org_counts = counts.argsort()# para organizar os numerios que se repetem
org_counts

array([0, 2, 3, 4, 1], dtype=int64)

In [104]:
values[org_counts]

array([0, 5, 7, 9, 3])

In [107]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'Valeur {i} apparait {j}')

Valeur 0 apparait 1
Valeur 5 apparait 1
Valeur 7 apparait 1
Valeur 9 apparait 1
Valeur 3 apparait 2


# NAN Correction

In [109]:
A = np.random.randn(5,5)
A[0,2] = np.nan
A[4, 3] = np.nan
A

array([[-0.7827755 , -0.44423283,         nan, -0.88180055, -0.44265324],
       [-0.5409163 , -1.32322737, -0.11279892,  0.90734594,  0.81526991],
       [ 0.22909795, -1.02617878,  0.47752547,  1.29269823, -0.73145824],
       [-1.60540226,  0.98947618,  0.11081461, -0.38093141,  0.11495917],
       [ 0.34531264, -1.73495876,  1.65835111,         nan, -0.47113526]])

In [117]:
A.sum()

nan

In [116]:
np.nanmean(A) # Ele faz calculos da media ignorando o nan

-0.1538094874997439

In [119]:
np.isnan(A).sum()

2

In [121]:
np.isnan(A).sum()/A.size

0.08

In [129]:
A[np.isnan(A)] = 0

In [133]:
A.mean()

-0.1415047284997644

# Algebra Linear

In [135]:
x = np.arange(20).reshape(5,4) 
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [137]:
x.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [142]:
x = x.transpose()